do not bail out if ssh not present

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -35,5 +35,5 @@ jobs:
         echo "$SSH_KEY" > ~/.ssh/id_rsa
         chmod 400 ~/.ssh/id_rsa
         echo $PATH
-        which ssh
+        which ssh || echo 'failed to find ssh'
         rsync -az _site/ jeremyphoward@ps625762.dreamhostps.com:fastcore.fast.ai/
